### ISSUE TITLE
installing deps issuing error on Windows

### ISSUE THREAD

**Issue by hassaanz** [Staffbase/create-staffbase-plugin-nodejs#4]
`An error occured. { Error: spawn npm ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install' ],
  cmd: 'npm install' }`

Getting an error after template is generated. Possibly windows unable to resolve the path to the generated folder.

**Comment by erikstagg** [comment]
I am getting a similar error:

`Installing dependencies...
An error occured. { Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install' ],
  cmd: 'npm install' }`

**Comment by axdotl** [comment]
Closed, will be archived.
